### PR TITLE
Add RouteMismatch constructor for arbitrary HTTP response code

### PR DESCRIPTION
**Pull request by thsutton**
This allows `HasServer` instances fail with a more-specific HTTP error code.

### CODE REVIEW

**Comment by jkarni** [comment]
Sounds good. OTOH it seems like we can simplify things quite a bit now, and just have

```
data RouteMismatch = RouteMismatch Int Status Message
```
and 

```
instance Ord RouteMismatch where
      RouteMismatch a _ _ <= RouteMismatch b _ _ = a <= b

instance Monoid RouteMismatch where
      mempty = RouteMismatch 0 NotFound ""
      mappend = max
```
So that all constructors can be merged into one. (I also had been thinking that defining the monoid in terms of the ord would have been more intuitive all along.) Alternatively, if we think there's a fixed ordering in all circumstances for status, we could give the status and ord instance and drop the `Int` constructor.

@alpmestan what do you think?

**Comment by thsutton** [comment]
Putting the `Int` in is a bit conceptually ugly, but far superior IMHO than just piggybacking on `Status(statusCode)`.

**Comment by jkarni** [comment]
Actually, `Rational` or some such might be better. I think we want the property that between any two RouteMismatches, there is/can be another.

**Comment by alpmestan** [comment]
What would `1%2` mean there?

**Comment by jkarni** [comment]
something that has higher priority in the monoid instance than 1%3, but lower than 2%3?

Ok, I agree this is getting excessive...

**Comment by alpmestan** [comment]
So the annoying thing here is that we would have to look at all the other types of "mismatches" to know what value to put there for ours. I understand however that having it has a fixed ADT with a fixed number of constructors is getting annoying for folks that want to extend the routing mechanism, and your solution brings a conceptually nice type with sound instances on the table -- I really only came up with the RouteMismatch monoid to have a small but working solution that would prevent logic errors on my part. And you're right it's time to rework it -- but can we come up with a better idea than one that forces us to look at the values for all other stuffs in order to put the right one for the one we add? This makes me think of how one picks the fixity of an operator =)

**Comment by jkarni** [comment]
@thsutton can you explain the use case? It might help with deciding what design is best.

**Comment by thsutton** [comment]
@jkarni Sure! We have a number of types which check do more than just plumb values through to a handler function and most of then need to return specific failures. Perhaps the most obvious is related to authentication: `TokenScope "foo"` check the following conditions:

1. That the Authorization header is set;
2. That it contains a valid token;
3. That the token has a scope which contains "foo"

When these conditions are not met we need to fail with a `RouteMismatch` so that the next route (possibly with different token scope requirements) can be attempted, but we also want to return a HTTP status code which is indicative of the actual error `401 Unauthorized`, `403 Forbidden`, etc.

Alternatives include:

1. Doing this sort of validation in the handler functions instead;

2. Just accept that `404 Not Found` means "computer says no" and move on.

We were doing (1) before but this leaves scope for users to forget to implement a check and leaves the API type, generated docs, and server implementation being consistent by coincidence rather than by construction.

**Comment by jkarni** [comment]
@thsutton thanks! We'll merge, and create a ticket for eventually figuring out how to generalize this further.

**Pull request merged**
