### PR TITLE
Export `toApplication` from Server.

### PR DESCRIPTION
**Pull request by mf59816**
This is useful for writing custom warp servers that do
things other than routing (e.g. dumping all requests and
responses to a file).

### CODE REVIEW

**Comment by alpmestan** [comment]
Interesting use  case. Sounds good to me. @jkarni the travis build fails because *servant-server*'s `Servant` module tries to export `Servant.QQ` which isn't there anymore, so this PR should be good to merge.

**Comment by jkarni** [comment]
I'm about to merge #13 - I'll have travis rebuild then, and merge if it passes.

**Comment by jkarni** [comment]
Looks good. Could  you rebase (and possibly add another `-- *` section)?

**Comment by jkarni** [comment]
Thanks!

**Pull request merged**
